name: Apply the latest sink filter to GCP

on:
  # Uncomment this for a manual trigger in GitHub Workflow
  workflow_dispatch:

jobs:
  apply-terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Verify GCP Auth
      - name: Test GCP project access
        run: gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      # Step 4: Set GCP project ID
      - name: Set GCP Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Step 5: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Step 6: Terraform Init and Apply
      - name: Terraform Init and Apply
        env:
          TF_VAR_GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_GCP_REGION: ${{ secrets.GCP_REGION }}
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: ./cdr
